name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-8)
        DOCKER_TAG=${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY}:commit-${IMAGE_TAG//-/}
        docker build . --file Dockerfile --tag $DOCKER_TAG
        docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
        docker push $DOCKER_TAG
